blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfol import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self) -> str:
        return self.title

portfol/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfol/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

portfol/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfol/home.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends "portfol/base.html" %}

{% block content %}

{% load static %}

<title>Igor's Blog</title> 

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">Igor has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a id="all_blogs_links" href="{% url 'blog:detail' blog.id %}">
      <h2>{{ blog.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blog.date|date:'d M Y' }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}


{% endblock %}

blog/templates/blog/detail.html
{% extends "portfol/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.description|safe }}

{% endblock %}

portfol/templates/portfol/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfol/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'portfol/panda.png' %}">
</head>
<body>

    <!--Top Menu bar-->
    <div class="container-fluid text-center">
    <nav class="navbar navbar-expand-lg navbar-light bg-transparent my-3">
        <img src="{% static 'portfol/panda.png' %}" width="80" height="50">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">Igor's portfolio</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:all_blogs'%}">Blog</a>
              </li>
              
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Social Networks</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="https://www.instagram.com/misticmonk/" target="_blank"><img src="{% static 'portfol/instagram.jpg' %}" alt="" width="20" height="20"> Instagram</a></li>
                        <li><a class="dropdown-item" href="https://www.linkedin.com/in/igor-v-b90085211" target="_blank"><img src="{% static 'portfol/linkin.png' %}" alt="" width="20" height="20"> LinkedIn</a></li>
                        <li><a class="dropdown-item" href="https://github.com/Braincrack" target="_blank"><img src="{% static 'portfol/github.png' %}" alt="" width="20" height="20"> GitHub</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="{% static 'portfol/igor voronin CV.pdf' %}" target="_blank">Resume</a>
                </li>
            </ul>
                </div>
              </div>
        </div>
    </nav>
    </div>


<div class="container">
{% block content %}{% endblock %}

</div>




<!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

portfol/templates/portfol/home.html
{% extends 'portfol/base.html' %}
{% block content %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Igor's portfolio</title>



</head>

<body>
      
<div class="row justify-content-center my-3">
  <div class="col-4">

    <img src="{% static 'portfol/homephoto1.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Welcome to Igor's web page! 😎</h1>
  </div>
</div>
<h2 class="mt-2">Portfolio</h2>
<hr>

<div class="row">
  {% for project in projects %}
  <div class="col-lg-3 col-md-4">
    <div class="card">

      <img src="{{ project.image.url }}" class="img-fluid">


      <div class="card-body">
        <h5 class="card-title">{{ project.title }}</h5>
        <p class="card-text">{{ project.description }}</p>
        {% if project.url %}
        <a href="{{ project.url }}" class="btn btn-primary">{{ project.url }}</a>
        {% else %}
        <a href="#" class="btn btn-primary">Link to</a>
        {% endif %}
      </div>
    </div>
    </div>
  {% endfor %}
</div>




{% endblock %}



</body>
</html>>